pipeline {
    agent any
    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/m-maheshreddy/Java-Tomcat-Project.git"
            }
        }
		
	}
	
}
