
def getProjectName() {
    return 'JenkinsPipeline'
}

def getJDKVersion() {
    return 'jdk1.8.0_25'
}

def getMavenConfig() {
    return 'maven-config'
}

def getMavenLocation() {
    return 'M2_HOME'
}

pipeline {
    agent any
	
	 tools { 
        maven 'Maven 3.5.4' 
        jdk 'jdk8' 
        }
	
    stages {
        stage ('Clone') {
            steps {
                git branch: 'master', url: "https://github.com/m-maheshreddy/Java-Tomcat-Project.git"
            }
        }
	    
	 stage('Maven Install') {
            steps {
                script {
		// withMaven(globalMavenSettingsConfig: "$mavenConfig", jdk: "$JDKVersion", maven: "$mavenLocation") {	
                 bat 'mvn clean install'
               //   }
		}
	      }
	  }   
		
	}

}
